### PR TITLE
preliminary Footer added

### PR DESCRIPTION
**Pull request by Dricmoy**
Need to decide on requirements for the footer, can't decide what's needed and not so just made it really simple
image

### CODE REVIEW

**Comment by rayzhou4** [comment]
Maybe remove the discord for now, since our discord is for members only right now, otherwise just add the actual ratemystudyspot logo (can be found under components/assets in `website-legacy` repo) and you're good to go! 

Also, I'm planning on adding a linkedin and instagram page for our organization. So if you have time, could you create those accounts with the organization's member account (which should be located in the `setup` repo under website/view-deployment.md) and then add those two links in the footer as well? Just a basic setup is fine right now (appropriate pfp and bio, etc), thanks!

**Comment by Dricmoy** [comment]
Also it looks really bland, I guess we will change it as we go.

**Comment by rayzhou4** [comment]
fair enough haha, its looking good so far, make sure to also add functionality for the icons if you havent already too

@LeoShangTang @burtonjong @anthonyych4n what are your guys opinions on the design?

**Comment by burtonjong** [comment]
Looks good but I think in the footer we should also include some other things:

- A link to the about page
- A link for support (email)

You can choose between two styles that are used often

Amazon Prime just has it as links
image

AirBnB has headers, then the links listed below

So for us, it would be something like:
**Support**     |   **RateMyStudySpot**
Contact Us      |              About Us

image

@Dricmoy 
@rayzhou4

**Comment by Dricmoy** [comment]
Me and leo didn't know what links were needed, what about something like this then:
                                                                                     Support | RateMyStudySpot (logo)
                                                                                             Contact Us | About Us
________________________________________________________________________________________________________________________________________
@2024 Ratemystudyspot .Privacy .Terms                                                                English (CA) Discord Github Instagram  Linkedin

**Pull request closed without merging**
